### ISSUE TITLE
The game has a bug

### ISSUE THREAD

**Issue by goxr3plus** [NickSklA/Pink-Ponk-Web-Based-Game#1]
Even if you hit the ball the first time them it start infinetely from top right corner going doing ,so basically you can't play .

I tried on  => https://ponk-pink.netlify.com/

**Comment by NickSklA** [comment]
Thanks a lot for your comment @goxr3plus !
So basically when the "right" player hits the ball, the first time, something unexpected happens?
I am trying to understand the "infinite" behavior you are describing. I didn't have any issue like that before. 
Could you please provide me with some more details?

**Comment by goxr3plus** [comment]
Go to the link by yourself and try to play the game , is everything working correctly?

**Comment by goxr3plus** [comment]
I attached a gif :

![2019-07-12_16-35-45](https://user-images.githubusercontent.com/20374208/61131992-23571b80-a4c3-11e9-961a-6dea4d9e10b2.gif)

**Comment by NickSklA** [comment]
Oh god, okay!
The "left" player doesn't show up.. It has to be something with the browser size.. Cause when i minimize it on mine browser, i am having the same problem. Thanks again for noticing. I will try to fix it soon!

**Comment by goxr3plus** [comment]
@NickSklA  By the way we are in the same University same department i think :) Though i have finished .

**Comment by NickSklA** [comment]
Wow really? That's awesome!! I just finished third year. One more to go 😂 I think we are connected on LinkedIn? I remember that i found you from your awesome JavaFx Media Player project! 

By the way, i solved the bug! I was placing the "left" player using pixel units. (Totally bad practice)
You can try it again here: https://ponk-pink.netlify.com/
